version: '3.10'
services:
  django:
    build: .
    restart: on-failure
    volumes:
      - .:/app
    env_file:
      - ./.env
    entrypoint:
      - ./django-entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"


volumes:
  postgres_data:
