# Generated by Django 4.1 on 2022-08-22 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tag", "0001_initial"),
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="follow_requests",
            field=models.ManyToManyField(
                related_name="requests", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="followers",
            field=models.ManyToManyField(
                related_name="follows", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="tags",
            field=models.ManyToManyField(related_name="pages", to="tag.tag"),
        ),
    ]
