# Generated by Django 4.1 on 2022-09-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_permanently_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
