# Generated by Django 4.1 on 2022-09-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0001_initial"),
        ("page", "0003_page_is_permanently_blocked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="pages", to="tag.tag"),
        ),
    ]
